/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated;


import com.cuenta.contador.jooq_auto_generated.tables.Account;
import com.cuenta.contador.jooq_auto_generated.tables.Credentials;
import com.cuenta.contador.jooq_auto_generated.tables.FlywaySchemaHistory;
import com.cuenta.contador.jooq_auto_generated.tables.Session;
import com.cuenta.contador.jooq_auto_generated.tables.Transaction;
import com.cuenta.contador.jooq_auto_generated.tables.TransactionType;
import com.cuenta.contador.jooq_auto_generated.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Contadordb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contadordb</code>
     */
    public static final Contadordb CONTADORDB = new Contadordb();

    /**
     * The table <code>contadordb.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>contadordb.credentials</code>.
     */
    public final Credentials CREDENTIALS = Credentials.CREDENTIALS;

    /**
     * The table <code>contadordb.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>contadordb.session</code>.
     */
    public final Session SESSION = Session.SESSION;

    /**
     * The table <code>contadordb.transaction</code>.
     */
    public final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>contadordb.transaction_type</code>.
     */
    public final TransactionType TRANSACTION_TYPE = TransactionType.TRANSACTION_TYPE;

    /**
     * The table <code>contadordb.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Contadordb() {
        super("contadordb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Credentials.CREDENTIALS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Session.SESSION,
            Transaction.TRANSACTION,
            TransactionType.TRANSACTION_TYPE,
            User.USER
        );
    }
}
