/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated;


import com.cuenta.contador.jooq_auto_generated.tables.Account;
import com.cuenta.contador.jooq_auto_generated.tables.BudgetAllocation;
import com.cuenta.contador.jooq_auto_generated.tables.FlywaySchemaHistory;
import com.cuenta.contador.jooq_auto_generated.tables.Session;
import com.cuenta.contador.jooq_auto_generated.tables.Transaction;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in contadordb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TRANSACTION_ACCOUNT_ID = Internal.createIndex(DSL.name("account_id"), Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ACCOUNT_ID }, false);
    public static final Index BUDGET_ALLOCATION_BUDGET_ID = Internal.createIndex(DSL.name("budget_id"), BudgetAllocation.BUDGET_ALLOCATION, new OrderField[] { BudgetAllocation.BUDGET_ALLOCATION.BUDGET_ID }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index ACCOUNT_USER_ID = Internal.createIndex(DSL.name("user_id"), Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.USER_ID }, false);
    public static final Index TRANSACTION_USER_ID = Internal.createIndex(DSL.name("user_id"), Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.USER_ID }, false);
    public static final Index SESSION_USERNAME = Internal.createIndex(DSL.name("username"), Session.SESSION, new OrderField[] { Session.SESSION.USERNAME }, false);
}
