/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated;


import com.cuenta.contador.jooq_auto_generated.tables.Account;
import com.cuenta.contador.jooq_auto_generated.tables.Budget;
import com.cuenta.contador.jooq_auto_generated.tables.Credentials;
import com.cuenta.contador.jooq_auto_generated.tables.FlywaySchemaHistory;
import com.cuenta.contador.jooq_auto_generated.tables.Session;
import com.cuenta.contador.jooq_auto_generated.tables.Transaction;
import com.cuenta.contador.jooq_auto_generated.tables.TransactionType;
import com.cuenta.contador.jooq_auto_generated.tables.User;


/**
 * Convenience access to all tables in contadordb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>contadordb.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>contadordb.budget</code>.
     */
    public static final Budget BUDGET = Budget.BUDGET;

    /**
     * The table <code>contadordb.credentials</code>.
     */
    public static final Credentials CREDENTIALS = Credentials.CREDENTIALS;

    /**
     * The table <code>contadordb.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>contadordb.session</code>.
     */
    public static final Session SESSION = Session.SESSION;

    /**
     * The table <code>contadordb.transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>contadordb.transaction_type</code>.
     */
    public static final TransactionType TRANSACTION_TYPE = TransactionType.TRANSACTION_TYPE;

    /**
     * The table <code>contadordb.user</code>.
     */
    public static final User USER = User.USER;
}
