/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables;


import com.cuenta.contador.jooq_auto_generated.Contadordb;
import com.cuenta.contador.jooq_auto_generated.Indexes;
import com.cuenta.contador.jooq_auto_generated.Keys;
import com.cuenta.contador.jooq_auto_generated.tables.Budget.BudgetPath;
import com.cuenta.contador.jooq_auto_generated.tables.records.BudgetAllocationRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BudgetAllocation extends TableImpl<BudgetAllocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contadordb.budget_allocation</code>
     */
    public static final BudgetAllocation BUDGET_ALLOCATION = new BudgetAllocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BudgetAllocationRecord> getRecordType() {
        return BudgetAllocationRecord.class;
    }

    /**
     * The column <code>contadordb.budget_allocation.id</code>.
     */
    public final TableField<BudgetAllocationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>contadordb.budget_allocation.budget_id</code>.
     */
    public final TableField<BudgetAllocationRecord, Integer> BUDGET_ID = createField(DSL.name("budget_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>contadordb.budget_allocation.category</code>.
     */
    public final TableField<BudgetAllocationRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>contadordb.budget_allocation.amount</code>.
     */
    public final TableField<BudgetAllocationRecord, Double> AMOUNT = createField(DSL.name("amount"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>contadordb.budget_allocation.spent</code>.
     */
    public final TableField<BudgetAllocationRecord, Double> SPENT = createField(DSL.name("spent"), SQLDataType.DOUBLE.defaultValue(DSL.inline("0", SQLDataType.DOUBLE)), this, "");

    private BudgetAllocation(Name alias, Table<BudgetAllocationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BudgetAllocation(Name alias, Table<BudgetAllocationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>contadordb.budget_allocation</code> table
     * reference
     */
    public BudgetAllocation(String alias) {
        this(DSL.name(alias), BUDGET_ALLOCATION);
    }

    /**
     * Create an aliased <code>contadordb.budget_allocation</code> table
     * reference
     */
    public BudgetAllocation(Name alias) {
        this(alias, BUDGET_ALLOCATION);
    }

    /**
     * Create a <code>contadordb.budget_allocation</code> table reference
     */
    public BudgetAllocation() {
        this(DSL.name("budget_allocation"), null);
    }

    public <O extends Record> BudgetAllocation(Table<O> path, ForeignKey<O, BudgetAllocationRecord> childPath, InverseForeignKey<O, BudgetAllocationRecord> parentPath) {
        super(path, childPath, parentPath, BUDGET_ALLOCATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BudgetAllocationPath extends BudgetAllocation implements Path<BudgetAllocationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BudgetAllocationPath(Table<O> path, ForeignKey<O, BudgetAllocationRecord> childPath, InverseForeignKey<O, BudgetAllocationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BudgetAllocationPath(Name alias, Table<BudgetAllocationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BudgetAllocationPath as(String alias) {
            return new BudgetAllocationPath(DSL.name(alias), this);
        }

        @Override
        public BudgetAllocationPath as(Name alias) {
            return new BudgetAllocationPath(alias, this);
        }

        @Override
        public BudgetAllocationPath as(Table<?> alias) {
            return new BudgetAllocationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Contadordb.CONTADORDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BUDGET_ALLOCATION_BUDGET_ID);
    }

    @Override
    public Identity<BudgetAllocationRecord, Integer> getIdentity() {
        return (Identity<BudgetAllocationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BudgetAllocationRecord> getPrimaryKey() {
        return Keys.KEY_BUDGET_ALLOCATION_PRIMARY;
    }

    @Override
    public List<ForeignKey<BudgetAllocationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BUDGET_ALLOCATION_IBFK_1);
    }

    private transient BudgetPath _budget;

    /**
     * Get the implicit join path to the <code>contadordb.budget</code> table.
     */
    public BudgetPath budget() {
        if (_budget == null)
            _budget = new BudgetPath(this, Keys.BUDGET_ALLOCATION_IBFK_1, null);

        return _budget;
    }

    @Override
    public BudgetAllocation as(String alias) {
        return new BudgetAllocation(DSL.name(alias), this);
    }

    @Override
    public BudgetAllocation as(Name alias) {
        return new BudgetAllocation(alias, this);
    }

    @Override
    public BudgetAllocation as(Table<?> alias) {
        return new BudgetAllocation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BudgetAllocation rename(String name) {
        return new BudgetAllocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BudgetAllocation rename(Name name) {
        return new BudgetAllocation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BudgetAllocation rename(Table<?> name) {
        return new BudgetAllocation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BudgetAllocation where(Condition condition) {
        return new BudgetAllocation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BudgetAllocation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BudgetAllocation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BudgetAllocation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BudgetAllocation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BudgetAllocation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BudgetAllocation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BudgetAllocation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BudgetAllocation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BudgetAllocation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
