/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables;


import com.cuenta.contador.jooq_auto_generated.Contadordb;
import com.cuenta.contador.jooq_auto_generated.Keys;
import com.cuenta.contador.jooq_auto_generated.tables.BudgetAllocation.BudgetAllocationPath;
import com.cuenta.contador.jooq_auto_generated.tables.Credentials.CredentialsPath;
import com.cuenta.contador.jooq_auto_generated.tables.records.BudgetRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Budget extends TableImpl<BudgetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contadordb.budget</code>
     */
    public static final Budget BUDGET = new Budget();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BudgetRecord> getRecordType() {
        return BudgetRecord.class;
    }

    /**
     * The column <code>contadordb.budget.id</code>.
     */
    public final TableField<BudgetRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>contadordb.budget.user_id</code>.
     */
    public final TableField<BudgetRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>contadordb.budget.year</code>.
     */
    public final TableField<BudgetRecord, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>contadordb.budget.month_num</code>.
     */
    public final TableField<BudgetRecord, Byte> MONTH_NUM = createField(DSL.name("month_num"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>contadordb.budget.total_amount</code>.
     */
    public final TableField<BudgetRecord, Double> TOTAL_AMOUNT = createField(DSL.name("total_amount"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Budget(Name alias, Table<BudgetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Budget(Name alias, Table<BudgetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>contadordb.budget</code> table reference
     */
    public Budget(String alias) {
        this(DSL.name(alias), BUDGET);
    }

    /**
     * Create an aliased <code>contadordb.budget</code> table reference
     */
    public Budget(Name alias) {
        this(alias, BUDGET);
    }

    /**
     * Create a <code>contadordb.budget</code> table reference
     */
    public Budget() {
        this(DSL.name("budget"), null);
    }

    public <O extends Record> Budget(Table<O> path, ForeignKey<O, BudgetRecord> childPath, InverseForeignKey<O, BudgetRecord> parentPath) {
        super(path, childPath, parentPath, BUDGET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BudgetPath extends Budget implements Path<BudgetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BudgetPath(Table<O> path, ForeignKey<O, BudgetRecord> childPath, InverseForeignKey<O, BudgetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BudgetPath(Name alias, Table<BudgetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BudgetPath as(String alias) {
            return new BudgetPath(DSL.name(alias), this);
        }

        @Override
        public BudgetPath as(Name alias) {
            return new BudgetPath(alias, this);
        }

        @Override
        public BudgetPath as(Table<?> alias) {
            return new BudgetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Contadordb.CONTADORDB;
    }

    @Override
    public Identity<BudgetRecord, Integer> getIdentity() {
        return (Identity<BudgetRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BudgetRecord> getPrimaryKey() {
        return Keys.KEY_BUDGET_PRIMARY;
    }

    @Override
    public List<UniqueKey<BudgetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BUDGET_USER_ID);
    }

    @Override
    public List<ForeignKey<BudgetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BUDGET_IBFK_1);
    }

    private transient CredentialsPath _credentials;

    /**
     * Get the implicit join path to the <code>contadordb.credentials</code>
     * table.
     */
    public CredentialsPath credentials() {
        if (_credentials == null)
            _credentials = new CredentialsPath(this, Keys.BUDGET_IBFK_1, null);

        return _credentials;
    }

    private transient BudgetAllocationPath _budgetAllocation;

    /**
     * Get the implicit to-many join path to the
     * <code>contadordb.budget_allocation</code> table
     */
    public BudgetAllocationPath budgetAllocation() {
        if (_budgetAllocation == null)
            _budgetAllocation = new BudgetAllocationPath(this, null, Keys.BUDGET_ALLOCATION_IBFK_1.getInverseKey());

        return _budgetAllocation;
    }

    @Override
    public Budget as(String alias) {
        return new Budget(DSL.name(alias), this);
    }

    @Override
    public Budget as(Name alias) {
        return new Budget(alias, this);
    }

    @Override
    public Budget as(Table<?> alias) {
        return new Budget(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Budget rename(String name) {
        return new Budget(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Budget rename(Name name) {
        return new Budget(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Budget rename(Table<?> name) {
        return new Budget(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Budget where(Condition condition) {
        return new Budget(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Budget where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Budget where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Budget where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Budget where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Budget where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Budget where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Budget where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Budget whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Budget whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
