/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables;


import com.cuenta.contador.jooq_auto_generated.Contadordb;
import com.cuenta.contador.jooq_auto_generated.Keys;
import com.cuenta.contador.jooq_auto_generated.tables.records.TransactionTypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionType extends TableImpl<TransactionTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contadordb.transaction_type</code>
     */
    public static final TransactionType TRANSACTION_TYPE = new TransactionType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionTypeRecord> getRecordType() {
        return TransactionTypeRecord.class;
    }

    /**
     * The column <code>contadordb.transaction_type.id</code>.
     */
    public final TableField<TransactionTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>contadordb.transaction_type.name</code>.
     */
    public final TableField<TransactionTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private TransactionType(Name alias, Table<TransactionTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TransactionType(Name alias, Table<TransactionTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>contadordb.transaction_type</code> table
     * reference
     */
    public TransactionType(String alias) {
        this(DSL.name(alias), TRANSACTION_TYPE);
    }

    /**
     * Create an aliased <code>contadordb.transaction_type</code> table
     * reference
     */
    public TransactionType(Name alias) {
        this(alias, TRANSACTION_TYPE);
    }

    /**
     * Create a <code>contadordb.transaction_type</code> table reference
     */
    public TransactionType() {
        this(DSL.name("transaction_type"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Contadordb.CONTADORDB;
    }

    @Override
    public Identity<TransactionTypeRecord, Integer> getIdentity() {
        return (Identity<TransactionTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TransactionTypeRecord> getPrimaryKey() {
        return Keys.KEY_TRANSACTION_TYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<TransactionTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TRANSACTION_TYPE_NAME);
    }

    @Override
    public TransactionType as(String alias) {
        return new TransactionType(DSL.name(alias), this);
    }

    @Override
    public TransactionType as(Name alias) {
        return new TransactionType(alias, this);
    }

    @Override
    public TransactionType as(Table<?> alias) {
        return new TransactionType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionType rename(String name) {
        return new TransactionType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionType rename(Name name) {
        return new TransactionType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionType rename(Table<?> name) {
        return new TransactionType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Condition condition) {
        return new TransactionType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
