/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables.records;


import com.cuenta.contador.jooq_auto_generated.tables.Account;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contadordb.account.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>contadordb.account.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>contadordb.account.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>contadordb.account.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>contadordb.account.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contadordb.account.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contadordb.account.number</code>.
     */
    public void setNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>contadordb.account.number</code>.
     */
    public String getNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>contadordb.account.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>contadordb.account.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>contadordb.account.balance</code>.
     */
    public void setBalance(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>contadordb.account.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Integer id, Integer userId, String name, String number, String type, Double balance) {
        super(Account.ACCOUNT);

        setId(id);
        setUserId(userId);
        setName(name);
        setNumber(number);
        setType(type);
        setBalance(balance);
        resetChangedOnNotNull();
    }
}
