/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables.records;


import com.cuenta.contador.jooq_auto_generated.tables.BudgetAllocation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BudgetAllocationRecord extends UpdatableRecordImpl<BudgetAllocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contadordb.budget_allocation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>contadordb.budget_allocation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>contadordb.budget_allocation.budget_id</code>.
     */
    public void setBudgetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>contadordb.budget_allocation.budget_id</code>.
     */
    public Integer getBudgetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>contadordb.budget_allocation.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contadordb.budget_allocation.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contadordb.budget_allocation.amount</code>.
     */
    public void setAmount(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>contadordb.budget_allocation.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>contadordb.budget_allocation.spent</code>.
     */
    public void setSpent(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>contadordb.budget_allocation.spent</code>.
     */
    public Double getSpent() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BudgetAllocationRecord
     */
    public BudgetAllocationRecord() {
        super(BudgetAllocation.BUDGET_ALLOCATION);
    }

    /**
     * Create a detached, initialised BudgetAllocationRecord
     */
    public BudgetAllocationRecord(Integer id, Integer budgetId, String category, Double amount, Double spent) {
        super(BudgetAllocation.BUDGET_ALLOCATION);

        setId(id);
        setBudgetId(budgetId);
        setCategory(category);
        setAmount(amount);
        setSpent(spent);
        resetChangedOnNotNull();
    }
}
