/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables.records;


import com.cuenta.contador.jooq_auto_generated.tables.Budget;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BudgetRecord extends UpdatableRecordImpl<BudgetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contadordb.budget.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>contadordb.budget.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>contadordb.budget.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>contadordb.budget.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>contadordb.budget.year</code>.
     */
    public void setYear(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>contadordb.budget.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>contadordb.budget.month_num</code>.
     */
    public void setMonthNum(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>contadordb.budget.month_num</code>.
     */
    public Byte getMonthNum() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>contadordb.budget.total_amount</code>.
     */
    public void setTotalAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>contadordb.budget.total_amount</code>.
     */
    public Double getTotalAmount() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BudgetRecord
     */
    public BudgetRecord() {
        super(Budget.BUDGET);
    }

    /**
     * Create a detached, initialised BudgetRecord
     */
    public BudgetRecord(Integer id, Integer userId, Integer year, Byte monthNum, Double totalAmount) {
        super(Budget.BUDGET);

        setId(id);
        setUserId(userId);
        setYear(year);
        setMonthNum(monthNum);
        setTotalAmount(totalAmount);
        resetChangedOnNotNull();
    }
}
