/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables.records;


import com.cuenta.contador.jooq_auto_generated.tables.Session;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionRecord extends UpdatableRecordImpl<SessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contadordb.session.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>contadordb.session.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>contadordb.session.session</code>.
     */
    public void setSession(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>contadordb.session.session</code>.
     */
    public String getSession() {
        return (String) get(1);
    }

    /**
     * Setter for <code>contadordb.session.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contadordb.session.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contadordb.session.expires_on</code>.
     */
    public void setExpiresOn(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>contadordb.session.expires_on</code>.
     */
    public LocalDateTime getExpiresOn() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRecord
     */
    public SessionRecord() {
        super(Session.SESSION);
    }

    /**
     * Create a detached, initialised SessionRecord
     */
    public SessionRecord(Integer id, String session, String username, LocalDateTime expiresOn) {
        super(Session.SESSION);

        setId(id);
        setSession(session);
        setUsername(username);
        setExpiresOn(expiresOn);
        resetChangedOnNotNull();
    }
}
