/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables.records;


import com.cuenta.contador.jooq_auto_generated.tables.Transaction;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contadordb.transaction.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>contadordb.transaction.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>contadordb.transaction.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>contadordb.transaction.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>contadordb.transaction.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contadordb.transaction.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contadordb.transaction.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>contadordb.transaction.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>contadordb.transaction.amount</code>.
     */
    public void setAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>contadordb.transaction.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>contadordb.transaction.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>contadordb.transaction.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>contadordb.transaction.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>contadordb.transaction.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION);
    }

    /**
     * Create a detached, initialised TransactionRecord
     */
    public TransactionRecord(Integer id, Integer userId, String name, String type, Double amount, Integer accountId, LocalDateTime createdOn) {
        super(Transaction.TRANSACTION);

        setId(id);
        setUserId(userId);
        setName(name);
        setType(type);
        setAmount(amount);
        setAccountId(accountId);
        setCreatedOn(createdOn);
        resetChangedOnNotNull();
    }
}
