/*
 * This file is generated by jOOQ.
 */
package com.cuenta.contador.jooq_auto_generated.tables.records;


import com.cuenta.contador.jooq_auto_generated.tables.TransactionType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionTypeRecord extends UpdatableRecordImpl<TransactionTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contadordb.transaction_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>contadordb.transaction_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>contadordb.transaction_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>contadordb.transaction_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionTypeRecord
     */
    public TransactionTypeRecord() {
        super(TransactionType.TRANSACTION_TYPE);
    }

    /**
     * Create a detached, initialised TransactionTypeRecord
     */
    public TransactionTypeRecord(Integer id, String name) {
        super(TransactionType.TRANSACTION_TYPE);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
